/**
 * @generated
 * @file Navigation (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://anderson-group-inc-main.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import DOM from "./webflow_modules/Builtin/components/DOM";
import DropdownList from "./webflow_modules/Dropdown/components/DropdownList";
import DropdownToggle from "./webflow_modules/Dropdown/components/DropdownToggle";
import DropdownWrapper from "./webflow_modules/Dropdown/components/DropdownWrapper";
import Grid from "./webflow_modules/Layout/components/Grid";
import Icon from "./webflow_modules/Icon/components/Icon";
import Image from "./webflow_modules/Basic/components/Image";
import Link from "./webflow_modules/Basic/components/Link";
import List from "./webflow_modules/Basic/components/List";
import ListItem from "./webflow_modules/Basic/components/ListItem";
import NavbarButton from "./webflow_modules/Navbar/components/NavbarButton";
import NavbarMenu from "./webflow_modules/Navbar/components/NavbarMenu";
import NavbarWrapper from "./webflow_modules/Navbar/components/NavbarWrapper";
import Paragraph from "./webflow_modules/Basic/components/Paragraph";
import Strong from "./webflow_modules/Basic/components/Strong";

/**
 * Props for {@link Navigation}
 */
export type NavigationProps = {};

/**
 * Navigation
 *
 * @see {@link https://anderson-group-inc-main.design.webflow.com | Source site in Webflow}
 */
export function Navigation({}: NavigationProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"nav is-inverse"} tag={"div"}>
        <NavbarWrapper
          className={"nav_container"}
          config={{
            easing: "ease",
            easing2: "ease",
            duration: 400,
            docHeight: false,
            noScroll: true,
            animation: "default",
            collapse: "medium",
          }}
          data-animation={"default"}
          data-collapse={"medium"}
          data-duration={"400"}
          data-easing={"ease"}
          data-easing2={"ease"}
          data-no-scroll={"1"}
          // @ts-ignore - User-defined custom attribute(s)
          role={"banner"}
          tag={"div"}
        >
          <Block
            className={"nav_left"}
            id={"w-node-_8af1b81b-694b-7796-7a6b-63978622a29c-7e6e1193"}
            tag={"div"}
          >
            <Link
              block={"inline"}
              button={false}
              className={"nav_logo"}
              id={"w-node-_8af1b81b-694b-7796-7a6b-63978622a29b-7e6e1193"}
              options={{
                href: "/",
              }}
            >
              <Image
                className={"image_contain"}
                loading={"lazy"}
                src={
                  "https://cdn.prod.website-files.com/6aad53d281964788243d8b20/6aad53d281964788243d8b75_AndersonGroup-logo-01.png"
                }
              />
            </Link>
          </Block>
          <Block
            className={"nav_right"}
            id={"w-node-_8af1b81b-694b-7796-7a6b-63978622a34e-7e6e1193"}
            tag={"div"}
          >
            <NavbarMenu
              className={"nav_menu"}
              id={"w-node-_8af1b81b-694b-7796-7a6b-63978622a349-7e6e1193"}
              role={"navigation"}
              tag={"nav"}
            >
              <List
                className={"nav_menu-list"}
                // @ts-ignore - User-defined custom attribute(s)
                role={"list"}
                tag={"ul"}
                unstyled={true}
              >
                <ListItem className={"nav_menu-list-item"}>
                  <DropdownWrapper
                    className={"nav_dropdown-menu"}
                    delay={0}
                    hover={false}
                    tag={"div"}
                  >
                    <DropdownToggle
                      className={"nav_link on-inverse"}
                      tag={"div"}
                    >
                      <Block tag={"div"}>{"Solutions"}</Block>
                      <Icon
                        className={"nav_caret"}
                        widget={{
                          type: "icon",
                          icon: "dropdown-toggle",
                        }}
                      />
                    </DropdownToggle>
                    <DropdownList
                      className={"mega-nav_dropdown-list"}
                      tag={"nav"}
                    >
                      <Block
                        className={"mega-nav_dropdown-list-wrapper"}
                        tag={"div"}
                      >
                        <List
                          className={
                            "grid_3-col tablet-1-col-1 gap-medium margin-bottom_none"
                          }
                          // @ts-ignore - User-defined custom attribute(s)
                          role={"list"}
                          tag={"ul"}
                          unstyled={true}
                        >
                          <ListItem
                            className={
                              "grid-item-manual w-node-_8af1b81b-694b-7796-7a6b-63978622a31a-7e6e1193"
                            }
                            id={
                              "w-node-_84f45f61-ef41-482d-a6f9-d55298effd85-ad6d2e56"
                            }
                          >
                            <Grid
                              className={"grid_3-col tablet-1-col-1 gap-small"}
                            >
                              <Block className={"grid-item-manual"} tag={"div"}>
                                <Block className={"eyebrow"} tag={"div"}>
                                  {"EXPLORE HOMES"}
                                </Block>
                                <List
                                  className={"mega-nav_list"}
                                  // @ts-ignore - User-defined custom attribute(s)
                                  role={"list"}
                                  tag={"ul"}
                                  unstyled={true}
                                >
                                  <ListItem
                                    id={
                                      "w-node-_8af1b81b-694b-7796-7a6b-63978622a2ae-7e6e1193"
                                    }
                                  >
                                    <Link
                                      block={"inline"}
                                      button={false}
                                      className={"mega-nav_link-item"}
                                      options={{
                                        href: "#",
                                      }}
                                    >
                                      <Block
                                        className={"nav_icon is-medium"}
                                        tag={"div"}
                                      >
                                        <DOM
                                          fill={"currentColor"}
                                          height={"100%"}
                                          tag={"svg"}
                                          viewBox={"0 0 32 32"}
                                          width={"100%"}
                                          xmlns={"http://www.w3.org/2000/svg"}
                                        >
                                          <DOM
                                            d={
                                              "m25.7 9.3l-7-7A.9.9 0 0 0 18 2H8a2.006 2.006 0 0 0-2 2v24a2.006 2.006 0 0 0 2 2h16a2.006 2.006 0 0 0 2-2V10a.9.9 0 0 0-.3-.7M18 4.4l5.6 5.6H18ZM24 28H8V4h8v6a2.006 2.006 0 0 0 2 2h6Z"
                                            }
                                            strokeLinejoin={"round"}
                                            tag={"path"}
                                          />
                                        </DOM>
                                      </Block>
                                      <Block
                                        className={
                                          "content-block w-node-_8af1b81b-694b-7796-7a6b-63978622a2ac-7e6e1193"
                                        }
                                        id={
                                          "w-node-_84f45f61-ef41-482d-a6f9-d55298effd90-ad6d2e56"
                                        }
                                        tag={"div"}
                                      >
                                        <Block tag={"div"}>
                                          <Strong>
                                            {"Available Listings"}
                                          </Strong>
                                        </Block>
                                        <Block
                                          className={"text-color_primary"}
                                          tag={"div"}
                                        >
                                          <Block
                                            className={
                                              "paragraph_small text-color_secondary"
                                            }
                                            tag={"div"}
                                          >
                                            {
                                              "Find your next home among our California properties."
                                            }
                                          </Block>
                                        </Block>
                                      </Block>
                                    </Link>
                                  </ListItem>
                                  <ListItem
                                    id={
                                      "w-node-_8af1b81b-694b-7796-7a6b-63978622a2ba-7e6e1193"
                                    }
                                  >
                                    <Link
                                      block={"inline"}
                                      button={false}
                                      className={"mega-nav_link-item"}
                                      options={{
                                        href: "#",
                                      }}
                                    >
                                      <Block
                                        className={"nav_icon is-medium"}
                                        tag={"div"}
                                      >
                                        <DOM
                                          fill={"currentColor"}
                                          height={"100%"}
                                          tag={"svg"}
                                          viewBox={"0 0 32 32"}
                                          width={"100%"}
                                          xmlns={"http://www.w3.org/2000/svg"}
                                        >
                                          <DOM
                                            d={
                                              "m25.7 9.3l-7-7A.9.9 0 0 0 18 2H8a2.006 2.006 0 0 0-2 2v24a2.006 2.006 0 0 0 2 2h16a2.006 2.006 0 0 0 2-2V10a.9.9 0 0 0-.3-.7M18 4.4l5.6 5.6H18ZM24 28H8V4h8v6a2.006 2.006 0 0 0 2 2h6Z"
                                            }
                                            strokeLinejoin={"round"}
                                            tag={"path"}
                                          />
                                        </DOM>
                                      </Block>
                                      <Block
                                        className={
                                          "content-block w-node-_8af1b81b-694b-7796-7a6b-63978622a2b8-7e6e1193"
                                        }
                                        id={
                                          "w-node-_84f45f61-ef41-482d-a6f9-d55298effd9c-ad6d2e56"
                                        }
                                        tag={"div"}
                                      >
                                        <Block tag={"div"}>
                                          <Strong>
                                            {"Featured Properties"}
                                          </Strong>
                                        </Block>
                                        <Block
                                          className={"text-color_primary"}
                                          tag={"div"}
                                        >
                                          <Block
                                            className={
                                              "paragraph_small text-color_secondary"
                                            }
                                            tag={"div"}
                                          >
                                            {
                                              "Explore standout homes with exceptional design and character."
                                            }
                                          </Block>
                                        </Block>
                                      </Block>
                                    </Link>
                                  </ListItem>
                                  <ListItem
                                    id={
                                      "w-node-_8af1b81b-694b-7796-7a6b-63978622a2c6-7e6e1193"
                                    }
                                  >
                                    <Link
                                      block={"inline"}
                                      button={false}
                                      className={"mega-nav_link-item"}
                                      options={{
                                        href: "#",
                                      }}
                                    >
                                      <Block
                                        className={"nav_icon is-medium"}
                                        tag={"div"}
                                      >
                                        <DOM
                                          fill={"currentColor"}
                                          height={"100%"}
                                          tag={"svg"}
                                          viewBox={"0 0 32 32"}
                                          width={"100%"}
                                          xmlns={"http://www.w3.org/2000/svg"}
                                        >
                                          <DOM
                                            d={
                                              "m25.7 9.3l-7-7A.9.9 0 0 0 18 2H8a2.006 2.006 0 0 0-2 2v24a2.006 2.006 0 0 0 2 2h16a2.006 2.006 0 0 0 2-2V10a.9.9 0 0 0-.3-.7M18 4.4l5.6 5.6H18ZM24 28H8V4h8v6a2.006 2.006 0 0 0 2 2h6Z"
                                            }
                                            strokeLinejoin={"round"}
                                            tag={"path"}
                                          />
                                        </DOM>
                                      </Block>
                                      <Block
                                        className={
                                          "content-block w-node-_8af1b81b-694b-7796-7a6b-63978622a2c4-7e6e1193"
                                        }
                                        id={
                                          "w-node-_84f45f61-ef41-482d-a6f9-d55298effda8-ad6d2e56"
                                        }
                                        tag={"div"}
                                      >
                                        <Block tag={"div"}>
                                          <Strong>{"Neighborhoods"}</Strong>
                                        </Block>
                                        <Block
                                          className={"text-color_primary"}
                                          tag={"div"}
                                        >
                                          <Block
                                            className={
                                              "paragraph_small text-color_secondary"
                                            }
                                            tag={"div"}
                                          >
                                            {
                                              "Discover the communities that make California feel like home."
                                            }
                                          </Block>
                                        </Block>
                                      </Block>
                                    </Link>
                                  </ListItem>
                                </List>
                              </Block>
                              <Block
                                className={"grid-item-manual"}
                                id={
                                  "w-node-_8af1b81b-694b-7796-7a6b-63978622a2f0-7e6e1193"
                                }
                                tag={"div"}
                              >
                                <Block className={"eyebrow"} tag={"div"}>
                                  {"OUR SERVICES"}
                                </Block>
                                <List
                                  className={"mega-nav_list"}
                                  // @ts-ignore - User-defined custom attribute(s)
                                  role={"list"}
                                  tag={"ul"}
                                  unstyled={true}
                                >
                                  <ListItem
                                    id={
                                      "w-node-_8af1b81b-694b-7796-7a6b-63978622a2d6-7e6e1193"
                                    }
                                  >
                                    <Link
                                      block={"inline"}
                                      button={false}
                                      className={"mega-nav_link-item"}
                                      options={{
                                        href: "#",
                                      }}
                                    >
                                      <Block
                                        className={"nav_icon is-medium"}
                                        tag={"div"}
                                      >
                                        <DOM
                                          fill={"currentColor"}
                                          height={"100%"}
                                          tag={"svg"}
                                          viewBox={"0 0 32 32"}
                                          width={"100%"}
                                          xmlns={"http://www.w3.org/2000/svg"}
                                        >
                                          <DOM
                                            d={
                                              "m25.7 9.3l-7-7A.9.9 0 0 0 18 2H8a2.006 2.006 0 0 0-2 2v24a2.006 2.006 0 0 0 2 2h16a2.006 2.006 0 0 0 2-2V10a.9.9 0 0 0-.3-.7M18 4.4l5.6 5.6H18ZM24 28H8V4h8v6a2.006 2.006 0 0 0 2 2h6Z"
                                            }
                                            strokeLinejoin={"round"}
                                            tag={"path"}
                                          />
                                        </DOM>
                                      </Block>
                                      <Block
                                        className={
                                          "content-block w-node-_8af1b81b-694b-7796-7a6b-63978622a2d4-7e6e1193"
                                        }
                                        id={
                                          "w-node-_84f45f61-ef41-482d-a6f9-d55298effdb8-ad6d2e56"
                                        }
                                        tag={"div"}
                                      >
                                        <Block tag={"div"}>
                                          <Strong>{"Buy a Home"}</Strong>
                                        </Block>
                                        <Block
                                          className={"text-color_primary"}
                                          tag={"div"}
                                        >
                                          <Block
                                            className={
                                              "paragraph_small text-color_secondary"
                                            }
                                            tag={"div"}
                                          >
                                            {
                                              "Get thoughtful guidance at every step of your search."
                                            }
                                          </Block>
                                        </Block>
                                      </Block>
                                    </Link>
                                  </ListItem>
                                  <ListItem
                                    id={
                                      "w-node-_8af1b81b-694b-7796-7a6b-63978622a2e2-7e6e1193"
                                    }
                                  >
                                    <Link
                                      block={"inline"}
                                      button={false}
                                      className={"mega-nav_link-item"}
                                      options={{
                                        href: "#",
                                      }}
                                    >
                                      <Block
                                        className={"nav_icon is-medium"}
                                        tag={"div"}
                                      >
                                        <DOM
                                          fill={"currentColor"}
                                          height={"100%"}
                                          tag={"svg"}
                                          viewBox={"0 0 32 32"}
                                          width={"100%"}
                                          xmlns={"http://www.w3.org/2000/svg"}
                                        >
                                          <DOM
                                            d={
                                              "m25.7 9.3l-7-7A.9.9 0 0 0 18 2H8a2.006 2.006 0 0 0-2 2v24a2.006 2.006 0 0 0 2 2h16a2.006 2.006 0 0 0 2-2V10a.9.9 0 0 0-.3-.7M18 4.4l5.6 5.6H18ZM24 28H8V4h8v6a2.006 2.006 0 0 0 2 2h6Z"
                                            }
                                            strokeLinejoin={"round"}
                                            tag={"path"}
                                          />
                                        </DOM>
                                      </Block>
                                      <Block
                                        className={
                                          "content-block w-node-_8af1b81b-694b-7796-7a6b-63978622a2e0-7e6e1193"
                                        }
                                        id={
                                          "w-node-_84f45f61-ef41-482d-a6f9-d55298effdc4-ad6d2e56"
                                        }
                                        tag={"div"}
                                      >
                                        <Block tag={"div"}>
                                          <Strong>{"Sell Your Home"}</Strong>
                                        </Block>
                                        <Block
                                          className={"text-color_primary"}
                                          tag={"div"}
                                        >
                                          <Block
                                            className={
                                              "paragraph_small text-color_secondary"
                                            }
                                            tag={"div"}
                                          >
                                            {
                                              "Showcase your property and move forward with confidence."
                                            }
                                          </Block>
                                        </Block>
                                      </Block>
                                    </Link>
                                  </ListItem>
                                  <ListItem
                                    id={
                                      "w-node-_8af1b81b-694b-7796-7a6b-63978622a2ee-7e6e1193"
                                    }
                                  >
                                    <Link
                                      block={"inline"}
                                      button={false}
                                      className={"mega-nav_link-item"}
                                      options={{
                                        href: "#",
                                      }}
                                    >
                                      <Block
                                        className={"nav_icon is-medium"}
                                        tag={"div"}
                                      >
                                        <DOM
                                          fill={"currentColor"}
                                          height={"100%"}
                                          tag={"svg"}
                                          viewBox={"0 0 32 32"}
                                          width={"100%"}
                                          xmlns={"http://www.w3.org/2000/svg"}
                                        >
                                          <DOM
                                            d={
                                              "m25.7 9.3l-7-7A.9.9 0 0 0 18 2H8a2.006 2.006 0 0 0-2 2v24a2.006 2.006 0 0 0 2 2h16a2.006 2.006 0 0 0 2-2V10a.9.9 0 0 0-.3-.7M18 4.4l5.6 5.6H18ZM24 28H8V4h8v6a2.006 2.006 0 0 0 2 2h6Z"
                                            }
                                            strokeLinejoin={"round"}
                                            tag={"path"}
                                          />
                                        </DOM>
                                      </Block>
                                      <Block
                                        className={
                                          "content-block w-node-_8af1b81b-694b-7796-7a6b-63978622a2ec-7e6e1193"
                                        }
                                        id={
                                          "w-node-_84f45f61-ef41-482d-a6f9-d55298effdd0-ad6d2e56"
                                        }
                                        tag={"div"}
                                      >
                                        <Block tag={"div"}>
                                          <Strong>
                                            {"Property Management"}
                                          </Strong>
                                        </Block>
                                        <Block
                                          className={"text-color_primary"}
                                          tag={"div"}
                                        >
                                          <Block
                                            className={
                                              "paragraph_small text-color_secondary"
                                            }
                                            tag={"div"}
                                          >
                                            {
                                              "Keep your investment cared for, down to the details."
                                            }
                                          </Block>
                                        </Block>
                                      </Block>
                                    </Link>
                                  </ListItem>
                                </List>
                              </Block>
                              <Block
                                className={"grid-item-manual"}
                                id={
                                  "w-node-_8af1b81b-694b-7796-7a6b-63978622a318-7e6e1193"
                                }
                                tag={"div"}
                              >
                                <Block className={"eyebrow"} tag={"div"}>
                                  {"GET TO KNOW US"}
                                </Block>
                                <List
                                  className={"mega-nav_list"}
                                  // @ts-ignore - User-defined custom attribute(s)
                                  role={"list"}
                                  tag={"ul"}
                                  unstyled={true}
                                >
                                  <ListItem
                                    id={
                                      "w-node-_8af1b81b-694b-7796-7a6b-63978622a2fe-7e6e1193"
                                    }
                                  >
                                    <Link
                                      block={"inline"}
                                      button={false}
                                      className={"mega-nav_link-item"}
                                      options={{
                                        href: "#",
                                      }}
                                    >
                                      <Block
                                        className={"nav_icon is-medium"}
                                        tag={"div"}
                                      >
                                        <DOM
                                          fill={"currentColor"}
                                          height={"100%"}
                                          tag={"svg"}
                                          viewBox={"0 0 32 32"}
                                          width={"100%"}
                                          xmlns={"http://www.w3.org/2000/svg"}
                                        >
                                          <DOM
                                            d={
                                              "m25.7 9.3l-7-7A.9.9 0 0 0 18 2H8a2.006 2.006 0 0 0-2 2v24a2.006 2.006 0 0 0 2 2h16a2.006 2.006 0 0 0 2-2V10a.9.9 0 0 0-.3-.7M18 4.4l5.6 5.6H18ZM24 28H8V4h8v6a2.006 2.006 0 0 0 2 2h6Z"
                                            }
                                            strokeLinejoin={"round"}
                                            tag={"path"}
                                          />
                                        </DOM>
                                      </Block>
                                      <Block
                                        className={
                                          "content-block w-node-_8af1b81b-694b-7796-7a6b-63978622a2fc-7e6e1193"
                                        }
                                        id={
                                          "w-node-_84f45f61-ef41-482d-a6f9-d55298effde0-ad6d2e56"
                                        }
                                        tag={"div"}
                                      >
                                        <Block tag={"div"}>
                                          <Strong>{"Our Story"}</Strong>
                                        </Block>
                                        <Block
                                          className={"text-color_primary"}
                                          tag={"div"}
                                        >
                                          <Block
                                            className={
                                              "paragraph_small text-color_secondary"
                                            }
                                            tag={"div"}
                                          >
                                            {
                                              "Learn about our approach to homes, people, and place."
                                            }
                                          </Block>
                                        </Block>
                                      </Block>
                                    </Link>
                                  </ListItem>
                                  <ListItem
                                    id={
                                      "w-node-_8af1b81b-694b-7796-7a6b-63978622a30a-7e6e1193"
                                    }
                                  >
                                    <Link
                                      block={"inline"}
                                      button={false}
                                      className={"mega-nav_link-item"}
                                      options={{
                                        href: "#",
                                      }}
                                    >
                                      <Block
                                        className={"nav_icon is-medium"}
                                        tag={"div"}
                                      >
                                        <DOM
                                          fill={"currentColor"}
                                          height={"100%"}
                                          tag={"svg"}
                                          viewBox={"0 0 32 32"}
                                          width={"100%"}
                                          xmlns={"http://www.w3.org/2000/svg"}
                                        >
                                          <DOM
                                            d={
                                              "m25.7 9.3l-7-7A.9.9 0 0 0 18 2H8a2.006 2.006 0 0 0-2 2v24a2.006 2.006 0 0 0 2 2h16a2.006 2.006 0 0 0 2-2V10a.9.9 0 0 0-.3-.7M18 4.4l5.6 5.6H18ZM24 28H8V4h8v6a2.006 2.006 0 0 0 2 2h6Z"
                                            }
                                            strokeLinejoin={"round"}
                                            tag={"path"}
                                          />
                                        </DOM>
                                      </Block>
                                      <Block
                                        className={
                                          "content-block w-node-_8af1b81b-694b-7796-7a6b-63978622a308-7e6e1193"
                                        }
                                        id={
                                          "w-node-_84f45f61-ef41-482d-a6f9-d55298effdec-ad6d2e56"
                                        }
                                        tag={"div"}
                                      >
                                        <Block tag={"div"}>
                                          <Strong>{"Our Team"}</Strong>
                                        </Block>
                                        <Block
                                          className={"text-color_primary"}
                                          tag={"div"}
                                        >
                                          <Block
                                            className={
                                              "paragraph_small text-color_secondary"
                                            }
                                            tag={"div"}
                                          >
                                            {
                                              "Meet the people helping you make your next move."
                                            }
                                          </Block>
                                        </Block>
                                      </Block>
                                    </Link>
                                  </ListItem>
                                  <ListItem
                                    id={
                                      "w-node-_8af1b81b-694b-7796-7a6b-63978622a316-7e6e1193"
                                    }
                                  >
                                    <Link
                                      block={"inline"}
                                      button={false}
                                      className={"mega-nav_link-item"}
                                      options={{
                                        href: "#",
                                      }}
                                    >
                                      <Block
                                        className={"nav_icon is-medium"}
                                        tag={"div"}
                                      >
                                        <DOM
                                          fill={"currentColor"}
                                          height={"100%"}
                                          tag={"svg"}
                                          viewBox={"0 0 32 32"}
                                          width={"100%"}
                                          xmlns={"http://www.w3.org/2000/svg"}
                                        >
                                          <DOM
                                            d={
                                              "m25.7 9.3l-7-7A.9.9 0 0 0 18 2H8a2.006 2.006 0 0 0-2 2v24a2.006 2.006 0 0 0 2 2h16a2.006 2.006 0 0 0 2-2V10a.9.9 0 0 0-.3-.7M18 4.4l5.6 5.6H18ZM24 28H8V4h8v6a2.006 2.006 0 0 0 2 2h6Z"
                                            }
                                            strokeLinejoin={"round"}
                                            tag={"path"}
                                          />
                                        </DOM>
                                      </Block>
                                      <Block
                                        className={
                                          "content-block w-node-_8af1b81b-694b-7796-7a6b-63978622a314-7e6e1193"
                                        }
                                        id={
                                          "w-node-_84f45f61-ef41-482d-a6f9-d55298effdf8-ad6d2e56"
                                        }
                                        tag={"div"}
                                      >
                                        <Block tag={"div"}>
                                          <Strong>{"Contact Us"}</Strong>
                                        </Block>
                                        <Block
                                          className={"text-color_primary"}
                                          tag={"div"}
                                        >
                                          <Block
                                            className={
                                              "paragraph_small text-color_secondary"
                                            }
                                            tag={"div"}
                                          >
                                            {
                                              "Tell us what you’re looking for. Let’s start a conversation."
                                            }
                                          </Block>
                                        </Block>
                                      </Block>
                                    </Link>
                                  </ListItem>
                                </List>
                              </Block>
                            </Grid>
                          </ListItem>
                          <ListItem
                            className={
                              "grid-item-manual w-node-_8af1b81b-694b-7796-7a6b-63978622a329-7e6e1193"
                            }
                            id={
                              "w-node-_84f45f61-ef41-482d-a6f9-d55298effdff-ad6d2e56"
                            }
                          >
                            <Link
                              block={"inline"}
                              button={false}
                              className={"card-link is-inverse on-inverse"}
                              options={{
                                href: "#",
                              }}
                            >
                              <Block className={"card_body"} tag={"div"}>
                                <Block
                                  className={"heading_tertiary"}
                                  tag={"div"}
                                >
                                  {"This title should take two lines"}
                                </Block>
                                <Paragraph
                                  className={
                                    "paragraph_small text-color_inverse-secondary"
                                  }
                                >
                                  {
                                    "This is some text inside of a div that describes this content."
                                  }
                                </Paragraph>
                                <Block
                                  className={"margin_top-auto"}
                                  tag={"div"}
                                >
                                  <Block className={"button-group"} tag={"div"}>
                                    <Block
                                      className={
                                        "text-button is-secondary on-inverse"
                                      }
                                      tag={"div"}
                                    >
                                      <Block tag={"div"}>{"Link text"}</Block>
                                      <Block
                                        className={"button_icon"}
                                        tag={"div"}
                                      >
                                        <DOM
                                          fill={"none"}
                                          height={"100%"}
                                          tag={"svg"}
                                          viewBox={"0 0 16 16"}
                                          width={"100%"}
                                          xmlns={"http://www.w3.org/2000/svg"}
                                        >
                                          <DOM
                                            d={
                                              "M2 8H14.5M14.5 8L8.5 2M14.5 8L8.5 14"
                                            }
                                            stroke={"currentColor"}
                                            strokeLinejoin={"round"}
                                            strokeWidth={"2"}
                                            tag={"path"}
                                          />
                                        </DOM>
                                      </Block>
                                    </Block>
                                  </Block>
                                </Block>
                              </Block>
                            </Link>
                          </ListItem>
                        </List>
                      </Block>
                    </DropdownList>
                  </DropdownWrapper>
                </ListItem>
                <ListItem className={"nav_menu-list-item"}>
                  <Link
                    block={"inline"}
                    button={false}
                    className={"nav_link on-inverse"}
                    options={{
                      href: "#",
                    }}
                  >
                    <Block tag={"div"}>{"About Us"}</Block>
                  </Link>
                </ListItem>
                <ListItem className={"nav_menu-list-item"}>
                  <Link
                    block={"inline"}
                    button={false}
                    className={"nav_link on-inverse"}
                    options={{
                      href: "#",
                    }}
                  >
                    <Block tag={"div"}>{"Blog"}</Block>
                  </Link>
                </ListItem>
                <ListItem className={"nav_menu-list-item"}>
                  <Link
                    block={"inline"}
                    button={false}
                    className={"nav_link on-inverse"}
                    options={{
                      href: "/listings",
                    }}
                  >
                    <Block tag={"div"}>{"Listings"}</Block>
                  </Link>
                </ListItem>
              </List>
            </NavbarMenu>
            <Block className={"button-group margin-top_none"} tag={"div"}>
              <Link
                block={"inline"}
                button={false}
                className={"button on-inverse"}
                options={{
                  href: "/#contact",
                }}
              >
                <Block className={"button_label"} tag={"div"}>
                  {"Get in touch"}
                </Block>
              </Link>
            </Block>
          </Block>
          <NavbarButton className={"nav_mobile-menu-button"} tag={"div"}>
            <Block className={"icon on-inverse"} tag={"div"}>
              <DOM
                height={"24"}
                tag={"svg"}
                viewBox={"0 0 24 24"}
                width={"24"}
                xmlns={"http://www.w3.org/2000/svg"}
              >
                <DOM
                  className={"nc-icon-wrapper"}
                  fill={"none"}
                  stroke={"currentColor"}
                  strokeLinecap={"square"}
                  strokeLinejoin={"miter"}
                  strokeMiterlimit={"10"}
                  strokeWidth={"1.5"}
                  tag={"g"}
                >
                  <DOM
                    stroke={"currentColor"}
                    tag={"line"}
                    x1={"1"}
                    x2={"23"}
                    y1={"12"}
                    y2={"12"}
                  />
                  <DOM tag={"line"} x1={"1"} x2={"23"} y1={"5"} y2={"5"} />
                  <DOM tag={"line"} x1={"1"} x2={"23"} y1={"19"} y2={"19"} />
                </DOM>
              </DOM>
            </Block>
          </NavbarButton>
        </NavbarWrapper>
      </Block>
    </div>
  );
}
